# The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
# The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Determine if a given user input is a triangular number

def is_triangular(number):
    """ Returns true if a given number is a triangular. False otherwise """
    # We are going to build up our triangle numbers from scratch
    triangular_number = 0
    # Helper variable for our triangle numbers calculation
    natural_number = 1
    
    # Iterate until the triangle number either surpasses or equals the input number
    while triangular_number < number:
        triangular_number += natural_number
        natural_number += 1

    # If they are equal, then the given number belongs to the triangle numbers
    if triangular_number == number:
        return True
    else:
        return False


number = int(input("Enter a number and we will determine if it's a triangle number: "))
if is_triangular(number):
    print("Yes! It's a triangle number!")
else:
    print("It's NOT a triangle number!")